apiVersion: v1
kind: Service
metadata:
  name: mcp-service
  namespace: default
  labels:
    app: mcp
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: mcp