apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-config
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: mcp-nest-k8s
    meta.helm.sh/release-namespace: default
data:
  PORT: "3000"
  NODE_ENV: "production"
  SAP_BASE_URL: "http://s4h24.sap4practice.com:8024/sap/opu/odata/sap/"
  SAP_CLIENT: "100"
  SAP_TIMEOUT: "30000"
  SAP_VALIDATE_SSL: "false"
  SAP_ENABLE_CSRF: "false"
  
  # BTP Catalog Service Configuration
  CATALOG_ODATA_URL: "https://your-tenant.cfapps.region.hana.ondemand.com/catalog/api/v1"
  CATALOG_OAUTH_TOKEN_URL: "https://your-tenant.authentication.region.hana.ondemand.com/oauth/token"
  
  # System Configuration Examples
  SYSTEM1_NAME: "Northwind Demo"
  SYSTEM1_TYPE: "generic_odata" 
  SYSTEM1_BASE_URL: "https://services.odata.org/V4/Northwind/Northwind.svc"
  SYSTEM1_AUTH_TYPE: "none"
  
  SYSTEM2_NAME: "BTP Catalog"
  SYSTEM2_TYPE: "btp"
  SYSTEM2_BASE_URL: "https://your-tenant.cfapps.region.hana.ondemand.com/catalog/api/v1"
  SYSTEM2_AUTH_TYPE: "oauth2"
---
apiVersion: v1
kind: Secret
metadata:
  name: mcp-secrets
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: mcp-nest-k8s
    meta.helm.sh/release-namespace: default
type: Opaque
stringData:
  SAP_USERNAME: "GVALER"
  SAP_PASSWORD: "Unisys.2019"
  
  # BTP OAuth Credentials
  CATALOG_OAUTH_CLIENT_ID: "your-btp-client-id"
  CATALOG_OAUTH_CLIENT_SECRET: "your-btp-client-secret"
  
  # System-specific OAuth credentials
  SYSTEM2_OAUTH_CLIENT_ID: "your-btp-client-id"
  SYSTEM2_OAUTH_CLIENT_SECRET: "your-btp-client-secret"