apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp
spec:
  replicas: 3  # Scale up for production
  template:
    spec:
      containers:
      - name: mcp
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: NODE_ENV
          value: "production"