apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: mcp-nest-server
  namespace: fleet-default
spec:
  # Repository configuration
  repo: https://github.com/Gheorghe-Valer/mcp.git
  branch: main
  paths:
  - mcp-nest/k8s/
  
  # Target clusters
  targets:
  - name: production
    clusterSelector:
      matchLabels:
        env: production
        
  # Environment-specific customizations
  targetCustomizations:
  - name: production
    clusterSelector:
      matchLabels:
        env: production
    kustomize:
      dir: mcp-nest/overlays/production